import SuperFilter from '../../../components/SuperFilter';
import Types from '../../../utils/filterTypes';
import { SummarySum } from '../../../components/Summary';
import IntegerFormat from '../../../components/NumeralFormat';

const columns = [
  {
    key: 'ordemProducao',
    name: 'OP',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    filterRenderer: SuperFilter,
    formatter: IntegerFormat,
    type: Types.NUMBER,
    order: 1,
    // locked: true
  },
  {
    key: 'ordemPrincipal',
    name: 'OP Pai',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    formatter: IntegerFormat,
    order: 2,
    // locked: true
  },
  {
    key: 'referenciaPeca',
    name: 'Grupo',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 3,
    // locked: true
  },
  {
    key: 'codDesPeriodo',
    name: 'Período',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 4,
    // locked: true
  },
  {
    key: 'proconfItem',
    name: 'Item',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 5,
    // locked: true
  },
  {
    key: 'descrColecao',
    name: 'Coleção',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 6,
    // locked: true
  },
  {
    key: 'descodEstagio',
    name: 'Estágio',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 7,
    // locked: true
  },
  {
    key: 'tempoDesdeEstagio',
    name: 'Dias',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    formatter: IntegerFormat,
    order: 8
  },
  {
    key: 'temSus',
    name: 'Tem SUS?',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 9
  },
  {
    key: 'desTipoOrdem',
    name: 'Tipo Ordem',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 10
  },
  {
    key: 'quemCosturou',
    name: 'Quem Costurou',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 11
  },
  {
    key: 'cargaPrograma',
    name: 'Carga Programa',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 12
  },
  {
    key: 'situacao',
    name: 'Situação',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 13
  },
  {
    key: 'minutoCostura',
    name: 'Minuto Costura',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    formatter: IntegerFormat,
    order: 14
  },
  {
    key: 'desDificuldade',
    name: 'Dificuldade Costura',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 15
  },
  {
    key: 'diasCostura',
    name: 'Dias Costura',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    formatter: IntegerFormat,
    order: 16
  },
  {
    key: 'descrSerie',
    name: 'Série Tamanho',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 17
  },
  {
    key: 'estacao',
    name: 'Estação',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 18
  },
  {
    key: 'marca',
    name: 'Marca',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 19
  },
  {
    key: 'paiCancelado',
    name: 'OP Pai Cancelado',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 20
  },
  {
    key: 'qtdFilhos',
    name: 'Qtd. Filhos',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    formatter: IntegerFormat,
    order: 21
  },
  {
    key: 'desOpUti',
    name: 'Tem UTI',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 21
  },
  {
    key: 'desTemLavacao',
    name: 'lavação',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 22
  },
  {
    key: 'qtdeProgramada',
    name: 'Programado',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    formatter: IntegerFormat,
    summary: SummarySum,
    order: 23
  },
  {
    key: 'qtdeProduzir',
    name: 'Produzir',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    formatter: IntegerFormat,
    summary: SummarySum,
    order: 24
  },
  {
    key: 'qtdeProduzida',
    name: 'Produzida',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    formatter: IntegerFormat,
    summary: SummarySum,
    order: 25
  },
  {
    key: 'qtdeSegunda',
    name: 'Qtde. Segunda',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    formatter: IntegerFormat,
    summary: SummarySum,
    order: 26
  },
  {
    key: 'qtdePerda',
    name: 'Qtde. Perda',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    formatter: IntegerFormat,
    summary: SummarySum,
    order: 27
  },
  {
    key: 'qtdeConserto',
    name: 'Qtde. Conserto',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    formatter: IntegerFormat,
    summary: SummarySum,
    order: 28
  },
  {
    key: 'qtdePendente',
    name: 'Qtde. Pendente',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    formatter: IntegerFormat,
    summary: SummarySum,
    order: 29
  },
  {
    key: 'artigoCotas',
    name: 'Artigo de Cotas',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 30
  },
  {
    key: 'opMesmaRefCor',
    name: 'OP. mesma Ref/Cor',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 31
  },
  {
    key: 'cancelouOp',
    name: 'Cancelou OP',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 32
  },
  {
    key: 'ordemServicoCostura',
    name: 'Ordem de Serviço de Costura',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    formatter: IntegerFormat,
    order: 33
  },
  {
    key: 'ordemServiço',
    name: 'Ordem de Serviço',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    formatter: IntegerFormat,
    order: 34
  },
  {
    key: 'nomeServicoEstagi',
    name: 'Nome Terceiro',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 35
  },
  {
    key: 'dataEmissaoOs',
    name: 'Data Emissão',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.DATE,
    order: 36
  },
  {
    key: 'dataPrevisaoOS',
    name: 'Data Previsão',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.DATA,
    order: 37
  },
  {
    key: 'dataProrrogacaoOS',
    name: 'Data Prorrogação',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.DATA,
    order: 38
  },
  {
    key: 'desCodfamilia',
    name: 'Des. Família',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 39
  },
  {
    key: 'responsavel',
    name: 'Responsável',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 40
  },
  {
    key: 'dataPrimBixaUltEst',
    name: 'Data Prim. Baixa Ult. Est.',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.DATE,
    order: 41
  },
  {
    key: 'semRoteiroCostura',
    name: 'Sem Roteiro Costura',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 42
  },
  {
    key: 'reservaZerada',
    name: 'Reserva Zerada',
    filterable: true,
    resizable: true,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 43
  }
];

export default columns;
