import SuperFilter from '../../../components/SuperFilter';
import Types from '../../../utils/filterTypes';
import { SummarySum } from '../../../components/Summary';
import IntegerFormat from '../../../components/NumeralFormat';

const columns = [
  {
    key: 'sequencia',
    name: 'Sequência',
    filterable: true,
    resizable: true,
    width: 130,
    hidden: false,
    sortable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    order: 1
  },
  {
    key: 'codigoEstagio',
    name: 'Estágio',
    filterable: true,
    resizable: true,
    width: 130,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    order: 2
  },
  {
    key: 'descricaoEstagio',
    name: 'Descrição Estágio',
    filterable: true,
    resizable: true,
    width: 200,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 3
  },
  {
    key: 'qtdeProgramada',
    name: 'Qtd. Programada',
    filterable: true,
    resizable: true,
    width: 130,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    order: 4
  },
  {
    key: 'qtdeProduzir',
    name: 'Qtd. Produzir',
    filterable: true,
    resizable: true,
    width: 130,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    order: 5
  },
  {
    key: 'qtdeProduzido',
    name: 'Qtd. Produzido',
    filterable: true,
    resizable: true,
    width: 130,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    order: 6
  },
  {
    key: 'qtdeSegunda',
    name: 'Qtd. Segunda',
    filterable: true,
    resizable: true,
    width: 130,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    order: 6
  },
  {
    key: 'qtdePerda',
    name: 'Qtd. Perda',
    filterable: true,
    resizable: true,
    width: 130,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    order: 7
  },
  {
    key: 'qtdeConserto',
    name: 'Qtd. Conserto',
    filterable: true,
    resizable: true,
    width: 130,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    order: 8
  },
  {
    key: 'qtdePendente',
    name: 'Qtd. Pendente',
    filterable: true,
    resizable: true,
    width: 130,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    order: 9
  },
  {
    key: 'diasEstagio',
    name: 'Dias Estágio',
    filterable: true,
    resizable: true,
    width: 130,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    order: 10
  },
  {
    key: 'dataEntrada',
    name: 'Data Entrada',
    filterable: true,
    resizable: true,
    width: 130,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.DATE,
    order: 11
  },
  {
    key: 'dataBaixa',
    name: 'Data Baixa',
    filterable: true,
    resizable: true,
    width: 130,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.DATE,
    order: 12
  },
  {
    key: 'horaEntrada',
    name: 'Hora Entrada',
    filterable: true,
    resizable: true,
    width: 130,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.DATE,
    order: 13
  },
  {
    key: 'horaBaixa',
    name: 'Hora Baixa',
    filterable: true,
    resizable: true,
    width: 130,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.NUMBER,
    order: 14
  },
  {
    key: 'usuario',
    name: 'Usuário',
    filterable: true,
    resizable: true,
    width: 130,
    hidden: false,
    sortable: true,
    draggable: true,
    filterRenderer: SuperFilter,
    type: Types.TEXT,
    order: 15
  }
];

export default columns;
